[workspace]
default-members = ["kube"]
members = [
  "kube",
  "kube-derive",
  "kube-runtime",

  # internal
  "tests",
  "examples",
]

[patch.crates-io.k8s-openapi]
git = "https://github.com/mikailbag/k8s-openapi"
branch = "expose-resource-name"