[workspace]
default-members = ["kube"]
members = [
  "kube",
  "kube-core",
  "kube-derive",
  "kube-runtime",

  # internal
  "tests",
  "examples",
]

[patch.crates-io]
k8s-openapi = { git = "https://github.com/Arnavion/k8s-openapi" }
