# Release process:
# 1. cargo release minor
# 2. verify that all crates are bumped and versions are in-line before proceeding
# 3a. await publishing - failures can happen due to still https://github.com/sunng87/cargo-release/issues/224
# 3b. fix failures from 3a (resume publishing manually, cd into dir, cargo publish, wait, continue for next in line)
# 4. check the consolidated commit (and commit message, templating fails now)
# 5. ./postrelease.sh

# Dependencies; cargo-release, cargo-tree, sd, ripgrep
consolidate-commits = true
no-dev-version = true # bumps happen right before release
pre-release-hook = ["../prerelease.sh"]

# Because of the potential failures in 3, we have to tag and push ourselves
disable-push = true
disable-tag = true
