[package]
name = "kube"
version = "0.35.1"
description = "Kubernetes client in futures controller runtime"
authors = [
  "clux <sszynrae@gmail.com>",
  "Teo Klestrup Röijezon <teo@nullable.se>",
  "ynqa <un.pensiero.vano@gmail.com>",
]
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
readme = "../README.md"
keywords = ["kubernetes", "client", "runtime", "reflector", "informer"]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies]
base64 = "0.12.1"
chrono = "0.4.11"
dirs = "2.0.2"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
serde_yaml = "0.8.12"
http = "0.2.1"
url = "2.1.1"
log = "0.4.8"
time = "0.2.16"
either = "1.5.3"
thiserror = "1.0.19"
futures-util = "0.3.5"
futures = "0.3.5"
pem = "0.8.1"
openssl = { version = "0.10.29", optional = true }
rustls = { version = "0.17.0", optional = true }
bytes = "0.5.4"
Inflector = "0.11.4"
tokio = { version = "0.2.21", features = ["time", "signal", "sync"] }

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["json", "gzip", "stream"]

[dependencies.k8s-openapi]
version = "0.8.0"
default-features = false
features = []

[features]
default = ["native-tls"]
native-tls = ["openssl", "reqwest/native-tls"]
rustls-tls = ["rustls", "reqwest/rustls-tls"]

[dev-dependencies]
kube-derive = { path = "../kube-derive" }
kube-runtime = { path = "../kube-runtime" }
tempfile = "3.1.0"
env_logger = "0.7.1"
tokio = { version = "0.2.21", features = ["full"] }
anyhow = "1.0.31"
color-eyre = "0.3.0"
snafu = { version = "0.6.8", features = ["futures"] }

[dev-dependencies.k8s-openapi]
version = "0.8.0"
default-features = false
features = ["v1_18"]
