[package]
name = "kube-runtime"
version = "0.46.0"
description = "Kubernetes futures controller runtime"
authors = [
  "Teo Klestrup Röijezon <teo@nullable.se>",
  "clux <sszynrae@gmail.com>",
]
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
keywords = ["kubernetes", "runtime", "reflector", "watcher", "controller"]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies]
futures = "0.3.5"
kube = { path = "../kube", version = "^0.46.0", default-features = false }
derivative = "2.1.1"
serde = "1.0.115"
smallvec = "1.4.2"
pin-project = "0.4.23"
tokio = { version = "~1.0", features = ["time"] }
tokio-util = {version = "0.6.0", features = ["time"]}
snafu = { version = "0.6.8", features = ["futures"] }
dashmap = "3.11.10"

[dependencies.k8s-openapi]
version = "0.10.0"
default-features = false

[features]
default = ["native-tls"]
native-tls = ["kube/native-tls"]
rustls-tls = ["kube/rustls-tls"]

[dev-dependencies.k8s-openapi]
version = "0.10.0"
default-features = false
features = ["v1_19"]

[dev-dependencies]
kube-derive = { path = "../kube-derive", version = "^0.46.0"}
serde_json = "1.0.57"
tokio = { version = "~1.0", features = ["full", "test-util"] }
rand = "0.7.3"
schemars = "0.8.0"
