name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract release info from CHANGELOG
        if: startsWith(github.ref, 'refs/tags/')
        run: grep $(date +%Y-%m-%d) -A 250 CHANGELOG.md | tail -n +3 | sed '1,/===================/!d' | head -n -3 > release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: release.txt
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        #if: startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo-tarpaulin
        #if: startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0'
          out-type: Lcov
          args: '--all -- --test-threads 1'
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
